O meu modo de fazer é esse
raphaborralho/receita-de-bolo pull request #1
Opened 2023-11-27 20:27 UTC by raphaborralho

2023-11-27 20:39 UTC, filipe85 requested changes

2023-11-27 20:39 UTC, filipe85 commented on receita-de-bolo.md
> +- colocar o trigo
O trigo precisa ser misturado junto com o ovo e manteiga.

2023-11-28 19:40 UTC, raphaborralho commented on receita-de-bolo.md
> +- colocar o trigo
blz, vou alterar no proximo commit

2023-11-28 19:44 UTC, filipe85 approved these changes

2023-11-28 19:53 UTC, merged